[package]
name = "unreal-keygen-core"
version = "0.1.0"
edition = "2024"
description = "Core library for generating Unreal Tournament CD keys"
authors = ["siohaza <siohaza@proton.me>"]

[dependencies]
rand = { workspace = true }
md-5 = { workspace = true }
