name: Deploy pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - name: Trunk build
        working-directory: unreal-keygen-web
        run: trunk build --release
      - name: Deploy to unreal-key.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'keyfrag.surge.sh'
          project: unreal-keygen-web/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
